### ISSUE TITLE
hackerman tries to prove the ts bot has some code that porewritten wrote but he forgot how licenses work

### ISSUE THREAD

**Issue by daggerdick69** [RocketDevelopmentStudios/toontown-2013#1]
![image](https://user-images.githubusercontent.com/40604202/41919048-973318d4-792b-11e8-9583-5872eece8b82.png)

Recognize this? ehh?
```
def handleConnected(self):
        if config.GetBool('send-hacker-test-message', False):
            self.logPotentialHacker('I am a test hacker message!', field='Test', thing='this')

```

Come on now, be original. 
You obviously copied the Pirates-Online-Rewritten/pirates/distributed/PiratesInternalRepository.py  code.
Stop claiming it's yours, stop bullshitting.

![image](https://user-images.githubusercontent.com/40604202/41919643-fe39ac86-792c-11e8-87aa-9bab0636804b.png)

As you can see, the repo has a license.

CAN YOU NOT FUCKING READ M8?

Violating the license is a crime, violation of the copyright law.

**Comment by toonjoey** [comment]
Look at the license permissions/limitations before you claim stuff. It allows for commercial use, modification, distribution, you get the idea. Just saying "Oh golly flippin' gee we have a license so you can't use AAAAAAANYTHING!" and not actually reading into said license is just wrong.

Even if it WAS stolen, there's no point in debating it because **the bot wont be used besides moderation, and will not be open sourced, released, etc.**

**Comment by toonjoey** [comment]
Also, I'm locking the conversation. Stop trying to argue about obvious memes, thanks.

**Comment by itsyaboyrocket** [comment]
hi internet

**Comment by itsyaboyrocket** [comment]
@daggerdick69

**Comment by itsyaboyrocket** [comment]
oh im sorry owen gonzalez*
